CREATE TABLE IF NOT EXISTS brand
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    fortress INTEGER,
    price    DECIMAL,
    CONSTRAINT pk_brand PRIMARY KEY (id)
);

CREATE INDEX fortress_index ON brand (fortress);