CREATE TABLE tobacco_and_taste
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tobacco_id BIGINT,
    taste_id   BIGINT,
    CONSTRAINT pk_tobaccoandtaste PRIMARY KEY (id)
);

ALTER TABLE tobacco_and_taste
    ADD CONSTRAINT FK_TOBACCOANDTASTE_ON_TASTE FOREIGN KEY (taste_id) REFERENCES taste (id);

ALTER TABLE tobacco_and_taste
    ADD CONSTRAINT FK_TOBACCOANDTASTE_ON_TOBACCO FOREIGN KEY (tobacco_id) REFERENCES tobacco (id);