CREATE TABLE IF NOT EXISTS taste
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_taste PRIMARY KEY (id)
);

CREATE INDEX name_index ON taste (name);