-- Миграция данных из старой структуры в новую

-- 1. Удаляем таблицу temp_tobacco (если она существует, она больше не нужна)
DROP TABLE IF EXISTS temp_tobacco CASCADE;

-- 2. Создаем таблицу delivery_tobacco (если её нет)
CREATE TABLE IF NOT EXISTS delivery_tobacco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    delivery_id BIGINT NOT NULL,
    tobacco_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_delivery_tobacco PRIMARY KEY (id),
    CONSTRAINT fk_delivery_tobacco_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_tobacco_tobacco FOREIGN KEY (tobacco_id) REFERENCES tobacco(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_delivery_tobacco_delivery ON delivery_tobacco(delivery_id);
CREATE INDEX IF NOT EXISTS idx_delivery_tobacco_tobacco ON delivery_tobacco(tobacco_id);

-- 3. Добавляем поле last_relevance_update (если его нет)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'tobacco' AND column_name = 'last_relevance_update') THEN
        ALTER TABLE tobacco ADD COLUMN last_relevance_update TIMESTAMP;
    END IF;
END $$;

-- 4. Создаем индекс для поиска уникальных табаков (если его нет)
CREATE INDEX IF NOT EXISTS idx_tobacco_brand_taste_weight_price ON tobacco(brand_name, taste, weight, price);

-- 5. Мигрируем данные из старой структуры в новую (только если есть поле delivery_id)
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns 
               WHERE table_name = 'tobacco' AND column_name = 'delivery_id') THEN
        
        -- Для каждого табака из завершенных привозов
        -- Создаем уникальные табаки в новой структуре и связи
        INSERT INTO delivery_tobacco (delivery_id, tobacco_id, quantity, created_at)
        SELECT DISTINCT
            t.delivery_id,
            t.id,
            1,
            CURRENT_TIMESTAMP
        FROM tobacco t
        WHERE t.delivery_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM delivery_tobacco dt 
            WHERE dt.delivery_id = t.delivery_id AND dt.tobacco_id = t.id
        );
        
        -- Удаляем поле delivery_id из tobacco
        ALTER TABLE tobacco DROP CONSTRAINT IF EXISTS fk_tobacco_delivery;
        ALTER TABLE tobacco DROP COLUMN IF EXISTS delivery_id;
    END IF;
END $$;
