CREATE TABLE IF NOT EXISTS tobacco
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price      DECIMAL,
    brand_name VARCHAR(255),
    fortress   INTEGER,
    CONSTRAINT pk_tobacco PRIMARY KEY (id)
);
CREATE INDEX brand_name_index ON tobacco (brand_name);