CREATE TABLE tobacco
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    price            DECIMAL,
    brand_name       VARCHAR(255),
    fortress         INTEGER,
    weight           INTEGER,
    order_date       date,
    inventory_date   date,
    inventory_weight INTEGER,
    taste            VARCHAR(255),
    CONSTRAINT pk_tobacco PRIMARY KEY (id)
);